version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    env_file: .env
    command: python run_bot.py

  app:
    build: .
    restart: unless-stopped
    env_file: .env
    command: python run_app.py
    ports:
      - "8081:8081"
